/*
 * @Date: 2021-10-15 14:09:17
 * @LastEditors: zhangheng
 * @LastEditTime: 2021-11-04 16:55:59
 */
export const CHANGE_SONG_INFO = 'CHANGE_SONG_INFO';
export const CHANGE_SONG_LYRIC = 'CHANGE_SONG_LYRIC';
export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG';
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST';
export const CHANGE_CURRENT_SONG_INDEX = 'CHANGE_CURRENT_SONG_INDEX';
export const CHANGE_SEQUENCE = 'CHANGE_SEQUENCE';
export const CHANGE_LYRIC_LIST = 'CHANGE_LYRIC_LIST';
export const CHANGE_CURRENT_LYRIC_INDEX = 'CHANGE_CURRENT_LYRIC_INDEX';
export const GLOBAL_PLAY_STATUS = 'GLOBAL_PLAY_STATUS';
