export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMENDS = 'CHANGE_HOT_RECOMMENDS';
export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS';

//榜单
export const CHANGE_NEW_SONGS = 'CHANGE_NEW_SONGS';
export const CHANGE_UP_SONGS = 'CHANGE_UP_SONGS';
export const CHANGE_ORIGINAL_SONGS = 'CHANGE_ORIGINAL_SONGS';

export const CHANGE_SETTLE_SINGERS = 'CHANGE_SETTLE_SINGERS';
export const CHANGE_HOT_ANCHORS = 'CHANGE_HOT_ANCHORS';
